// Code generated by Microsoft (R) AutoRest Code Generator 0.12.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Raci.B2C.Bicycle.ClientApi
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    public static partial class ReferenceDatasExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IList<ReferenceData> GetBicycleTypes(this IReferenceDatas operations)
            {
                return Task.Factory.StartNew(s => ((IReferenceDatas)s).GetBicycleTypesAsync(), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<ReferenceData>> GetBicycleTypesAsync( this IReferenceDatas operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                HttpOperationResponse<IList<ReferenceData>> result = await operations.GetBicycleTypesWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false);
                return result.Body;
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static MinMaxDTO GetSumInuredRange(this IReferenceDatas operations)
            {
                return Task.Factory.StartNew(s => ((IReferenceDatas)s).GetSumInuredRangeAsync(), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<MinMaxDTO> GetSumInuredRangeAsync( this IReferenceDatas operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                HttpOperationResponse<MinMaxDTO> result = await operations.GetSumInuredRangeWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false);
                return result.Body;
            }

    }
}
