// Code generated by Microsoft (R) AutoRest Code Generator 0.12.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Raci.B2C.Bicycle.ClientApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class AddressDTO
    {
        /// <summary>
        /// Initializes a new instance of the AddressDTO class.
        /// </summary>
        public AddressDTO() { }

        /// <summary>
        /// Initializes a new instance of the AddressDTO class.
        /// </summary>
        public AddressDTO(string addressLine1, string suburb, string postCode)
        {
            AddressLine1 = addressLine1;
            Suburb = suburb;
            PostCode = postCode;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "addressLine1")]
        public string AddressLine1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "suburb")]
        public string Suburb { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "postCode")]
        public string PostCode { get; set; }

        /// <summary>
        /// Validate the object. Throws ArgumentException or ArgumentNullException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (AddressLine1 == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "AddressLine1");
            }
            if (Suburb == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Suburb");
            }
            if (PostCode == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "PostCode");
            }
        }
    }
}
