// Code generated by Microsoft (R) AutoRest Code Generator 0.12.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Raci.B2C.Bicycle.ClientApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class MinMaxDTO
    {
        /// <summary>
        /// Initializes a new instance of the MinMaxDTO class.
        /// </summary>
        public MinMaxDTO() { }

        /// <summary>
        /// Initializes a new instance of the MinMaxDTO class.
        /// </summary>
        public MinMaxDTO(double? minValue = default(double?), double? maxValue = default(double?))
        {
            MinValue = minValue;
            MaxValue = maxValue;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "minValue")]
        public double? MinValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maxValue")]
        public double? MaxValue { get; set; }

    }
}
