// Code generated by Microsoft (R) AutoRest Code Generator 0.12.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Raci.B2C.Bicycle.ClientApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class PaymentDetailDTO
    {
        /// <summary>
        /// Initializes a new instance of the PaymentDetailDTO class.
        /// </summary>
        public PaymentDetailDTO() { }

        /// <summary>
        /// Initializes a new instance of the PaymentDetailDTO class.
        /// </summary>
        public PaymentDetailDTO(string transactionId = default(string))
        {
            TransactionId = transactionId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionId")]
        public string TransactionId { get; set; }

    }
}
