// Code generated by Microsoft (R) AutoRest Code Generator 0.12.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Raci.B2C.Bicycle.ClientApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class PolicyDTO
    {
        /// <summary>
        /// Initializes a new instance of the PolicyDTO class.
        /// </summary>
        public PolicyDTO() { }

        /// <summary>
        /// Initializes a new instance of the PolicyDTO class.
        /// </summary>
        public PolicyDTO(string policyNumber = default(string), long? id = default(long?), bool? isNew = default(bool?), bool? isQuote = default(bool?), bool? isPolicy = default(bool?), PolicyOptionDTO option = default(PolicyOptionDTO), PolicyContactDTO contact = default(PolicyContactDTO), BicyclePolicyDetailDTO detail = default(BicyclePolicyDetailDTO), PaymentDetailDTO payment = default(PaymentDetailDTO))
        {
            PolicyNumber = policyNumber;
            Id = id;
            IsNew = isNew;
            IsQuote = isQuote;
            IsPolicy = isPolicy;
            Option = option;
            Contact = contact;
            Detail = detail;
            Payment = payment;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "policyNumber")]
        public string PolicyNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isNew")]
        public bool? IsNew { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isQuote")]
        public bool? IsQuote { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isPolicy")]
        public bool? IsPolicy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "option")]
        public PolicyOptionDTO Option { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contact")]
        public PolicyContactDTO Contact { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "detail")]
        public BicyclePolicyDetailDTO Detail { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "payment")]
        public PaymentDetailDTO Payment { get; set; }

        /// <summary>
        /// Validate the object. Throws ArgumentException or ArgumentNullException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.Option != null)
            {
                this.Option.Validate();
            }
            if (this.Contact != null)
            {
                this.Contact.Validate();
            }
        }
    }
}
