// Code generated by Microsoft (R) AutoRest Code Generator 0.12.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Raci.B2C.Bicycle.ClientApi.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// </summary>
    public partial class ReferenceData
    {
        /// <summary>
        /// Initializes a new instance of the ReferenceData class.
        /// </summary>
        public ReferenceData() { }

        /// <summary>
        /// Initializes a new instance of the ReferenceData class.
        /// </summary>
        public ReferenceData(string id = default(string), string description = default(string))
        {
            Id = id;
            Description = description;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

    }
}
